export const recipe = {
  id: 782585,
  usedIngredientCount: 0,
  missedIngredientCount: 8,
  missedIngredients: [
    {
      id: 10016049,
      amount: 3.75,
      unit: 'cups',
      unitLong: 'cups',
      unitShort: 'cup',
      aisle: 'Pasta and Rice;Canned and Jarred',
      name: 'cannellini beans',
      original:
        '1 1/4 cups dried cannellini (white kidney) beans (3 3/4 cups cooked)',
      originalName: '1/4 cups dried cannellini (white kidney) beans cooked)',
      meta: ['dried', 'white', 'cooked', '( kidney)'],
      extendedName: 'cooked white dried cannellini beans',
      image:
        'https://spoonacular.com/cdn/ingredients_100x100/dry-cannellini-beans.jpg',
    },
    {
      id: 93604,
      amount: 1.0,
      unit: 'handful',
      unitLong: 'handful',
      unitShort: 'handful',
      aisle: 'Ethnic Foods',
      name: 'curry leaves',
      original: 'handful of dried curry leaves, crumbled (or 1 bay leaf)',
      originalName: 'dried curry leaves, crumbled (or 1 bay leaf)',
      meta: ['dried', 'crumbled', '(or 1 bay leaf)'],
      extendedName: 'dried curry leaves',
      image: 'https://spoonacular.com/cdn/ingredients_100x100/curry-leaves.jpg',
    },
    {
      id: 2041,
      amount: 0.25,
      unit: 'cup',
      unitLong: 'cups',
      unitShort: 'cup',
      aisle: 'Produce;Spices and Seasonings',
      name: 'tarragon',
      original: '1/4 cup fresh tarragon',
      originalName: 'fresh tarragon',
      meta: ['fresh'],
      extendedName: 'fresh tarragon',
      image: 'https://spoonacular.com/cdn/ingredients_100x100/tarragon.jpg',
    },
    {
      id: 11215,
      amount: 1.0,
      unit: 'clove',
      unitLong: 'clove',
      unitShort: 'clove',
      aisle: 'Produce',
      name: 'garlic',
      original: '1 clove garlic, minced or crushed',
      originalName: 'garlic, minced or crushed',
      meta: ['minced', 'crushed'],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/garlic.png',
    },
    {
      id: 9152,
      amount: 3.0,
      unit: '',
      unitLong: '',
      unitShort: '',
      aisle: 'Produce',
      name: 'juice of lemon',
      original: 'juice from 1 lemon (3 tablespoons)',
      originalName: 'juice from 1 lemon',
      meta: [],
      extendedName: 'lemon (juice)',
      image: 'https://spoonacular.com/cdn/ingredients_100x100/lemon-juice.jpg',
    },
    {
      id: 9156,
      amount: 1.0,
      unit: 'teaspoon',
      unitLong: 'teaspoon',
      unitShort: 'tsp',
      aisle: 'Produce',
      name: 'lemon zest',
      original: '1 teaspoon grated lemon zest',
      originalName: 'grated lemon zest',
      meta: ['grated'],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/zest-lemon.jpg',
    },
    {
      id: 11260,
      amount: 8.0,
      unit: 'large',
      unitLong: 'larges',
      unitShort: 'large',
      aisle: 'Produce',
      name: 'mushrooms',
      original: '8 large white mushrooms, sliced',
      originalName: 'white mushrooms, sliced',
      meta: ['white', 'sliced'],
      extendedName: 'white mushrooms',
      image: 'https://spoonacular.com/cdn/ingredients_100x100/mushrooms.png',
    },
    {
      id: 1012046,
      amount: 1.0,
      unit: 'teaspoons',
      unitLong: 'teaspoon',
      unitShort: 'tsp',
      aisle: 'Condiments',
      name: 'grain mustard',
      original: '1 to 1 1/2 teaspoons Dijon or grain mustard, to taste',
      originalName: 'Dijon or grain mustard, to taste',
      meta: ['to taste'],
      image:
        'https://spoonacular.com/cdn/ingredients_100x100/whole-grain-mustard.png',
    },
  ],
  likes: 0,
  usedIngredients: [],
  unusedIngredients: [],
  title: 'Cannellini Bean and Asparagus Salad with Mushrooms',
  image: 'https://spoonacular.com/recipeImages/782585-312x231.jpg',
  imageType: 'jpg',
}
